### ISSUE TITLE
CSS doesn't work.

### ISSUE THREAD

**Issue by neerajsharma1-appirio** [Yankovsky/static-heroku-nodejs#1]
It runs the HTML files but doesn't load the CSS.

**Comment by Yankovsky** [comment]
@neerajsharma1-appirio Hey! It's been a long time since I wrote this instruction. Glad that it still works and helps other folks out there.
To serve other file types you need to change app.js to something smarter and more flexible, because it only serves html files right now. I will update instruction later today.

**Comment by Yankovsky** [comment]
@neerajsharma1-appirio hey! I've updated readme, web server example and demo. Check it out!

**Comment by neerajsharma1-appirio** [comment]
Hi, @Yankovsky Thanks so much for the prompt response the CSS issue is fixed now :) but, it still doesn't serve the SVG images and shows path error for TTF and WOFF (font files I'm adding through CSS).

**Comment by Yankovsky** [comment]
@neerajsharma1-appirio It is probably because of the missing mime type. Try to use more advanced web server like [express](https://expressjs.com/en/starter/static-files.html), [http-server](https://github.com/http-party/http-server#readme) or maybe even drop node.js in favor of nginx.

**Comment by neerajsharma1-appirio** [comment]
Thanks @Yankovsky  I'll try the suggested solutions. Thanks again for the help.
Cheers!
